services:
  postgres:
    image: postgres:14.1-alpine
    container_name: dbt_postgres
    environment:
      POSTGRES_USER: dbt
      POSTGRES_PASSWORD: dbt
      POSTGRES_DB: dbt
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./
        target: /var/lib/postgresql/data
  # dbt:
  #   image: fishtownanalytics/dbt:1.1.1
  #   container_name: dbt
  #   working_dir: /usr/app
  #   volumes:
  #     - type: bind
  #       source: ./
  #       target: /usr/app
  #     - ./dbt:/usr/app
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres

# volumes:
#   postgres_data:
